---
sudo: required
dist: trusty
language: node_js
node_js:
- 7

cache:
  directories:
  - node_modules

before_install:
- npm install -g yarn
- wget https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
- mv boot.sh boot && chmod a+x boot && sudo mv boot /usr/local/bin

install:
- boot
- yarn install


script:
- yarn lint
- yarn type:check
- yarn test
- boot test
- boot release-ci
