sudo: required
dist: trusty
language: node_js
node_js:
- 7
cache:
  directories:
  - node_modules
  - "$HOME/.m2"
  - tmp
before_install:
- npm install -g yarn
- wget https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
- mv boot.sh boot && chmod a+x boot && sudo mv boot /usr/local/bin
install:
- boot
- yarn install
script:
- yarn lint
- yarn type:check
- yarn test
- boot test
- boot release-ci
addons:
  artifacts:
    paths:
    - "./main"
    target_paths: artifacts
env:
  global:
  # ARTIFACTS_KEY
  - secure: QeH3unClMlfVb1yU9IMd84YAPakq7IKipic9X3X8XLR1Orcmm/SyvA3d0xUvXvvDxmoy+7wekCClHM9+vTvENgOF3cy60iCfdzl1kAN/ZxC+EfiVL6JewawU8bUQL9de7oELp4bjq07A//H87y918HF4iCLGMASzGLQSIlXzLDOOh5iTz4YGZnpZQ+NNnbpmud4CaH7NxY4eFqyrOApeJ4gOD1S0WhXJNkoSjBToNij4PVnCkpcZu0O7CdLu/cyobzMDubJeMy2oXvamy/z25qZgrjqjPI+yDl0qiayLnkbCx45ufwU0KN3GHgWO/+kauAMI/L7UExqo0yHpbSThr+rpHVs3E+bYmyUvgAXyWLDKoh8flvGkb6vSnZxXVuRYlwAMnM9QARVVynazfMluskJa5W5llg13Ixg/hY8rKFIQXmANvq3uY3cuJXTcpTkJGXd6CKdnjrF58KvE4kYN/t2tMI8F/U9QWgi681bcKbABNORRn2BD9o4GBwy/GPfDCv5V8Jqs3fUtgy4Oqof0E2JL9Q66qfhDdish9U/to5wJw1Ul3quco/jpo/AjjvCac2yrJALZCg6YiWYOwenSqRof88vYDXR0s7AyN+ItneGc9lrLBUF+lTqZn1xpUhua1eNAwZS5nBenIopDulG40dZzRjYO4mQ5NWhAQ1KIOJw=
  # ARTIFACTS_SECRET
  - secure: CuENJrH/+oede/nhVNiebndGNZvfOqI6rTnRBiFbsAKYAGHoGjN/09rpF7LqH+mScsd5vmaKk/svkiC9msL6MDUJVEZ6Oyg982DMJfecyVhgiyuUB+XNjUBBq8tTmBzK0D0Tvae3SiCw0GQuW/fpkE+Qu8df/qg8tqoNIsFqdlbAtr2SHyS+WCduDnQ0bVHOMcZ1i6Djfq/igFeAKO7+mOfysrpu5ov3yIdAM4vlEoZhOL+ETMX4hWko09xrI7zLYbZHvnRRK8FF/GBLQSN2Im3smvABQetjfhKwSRZQ+qUUPotD2QFxkrg6qSR56I7qSBisNcGoKSV0T/+w7PVoe2kvbdbrAt6VYusT8g4/0ck5wUYjkEczGPTC7CW3/IhUThVQZtiTKOljGCg/Ien/QYri2VczkkJsvtmKsmamKBssItNJ2GTqt060f7GPXJfTt0dRIe/lWZK/5xBnzu70pxLDeXOOeWrct3j+2O2Vtg+wmjFUDylyiDVV9QKWAqTwWnoKbJ1Jp2Jtu9FGqGu48g04KEN1CAL0UnJyCzVG7Wtfv9k4HIK1pTmFRjZJODdwKlp5BHgLLqHzw0tP1mamGOXs5CpDVU/bSF1tdaoVYCUkeAu6GG2T4njzqraIZLc8OXCMtTiBNkDVArKpJ4SH/ony+bjRiMa6ugspC62H/ho=
  # ARTIFACTS_BUCKET
  - secure: SuJgZBrNJBsMsu6KV3Xyq9QBdRHpXWPc1nUVJWY2e+xu1+Noe4zC0GBlfTgUKiivtqlfpKumHmg3ybv3Py+iybQ0xtsPIhOx2tLFYZoSRPjz8uwRaaTyuz8gjNrY0QmsQfx5Yhdq6mJ+eC/qXLZSP8gfvQ7BDui5rudUrSyV3obn9T39J+Es9YGwGcvbESyW/IM08RrhSfiwM81kmNUgmP72gFm91+FSoiJHlmZyR4IADhuHmYErM2kpieIq7sIeINdmFztz5RjqKgbVmldJkZOkWAiG0ODqUbSlzm/+xdPL9gzyB2c5u864U4NgXSeQSdh6rbA/bSPd+tg5z5TTQe1CYa6fFUeGVG9weScdU69Y6XBpR2i+JXdej8lqlzup/1pczW6Rzux07B1hPsjQ7/lkXXWalykfa72goorm9+rzi0igYH8I08R5K6K0Uad6mArdgzI0MU/0gU7sZ/12UaNjMugAYyjrDGyzSKiWR1+Os1jCowJIp7wRr0679pmE6hb+2uU1tvUyNPvmKmUMwImVteFxmkUNj+XuN3fla6+/39LTHWK9eJTFV0Nwwcu01qVRSx4r0/Ijt7BQUjNWPFYvJo8Lt0Et8GuiLkRCXZKLhMwNs1UlJGYSQcDKl5iq7UEqcByOkxwBhMrokPTEhs4RPWwcGsh207WlftLGL8E=
